FROM node:16-slim

WORKDIR /app

COPY package*.json ./
COPY nodemon.json ./
COPY tsconfig.json ./
COPY tslint.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY src/ /app/src/

# RUN npm run build
EXPOSE 8080
CMD npm run live

# CMD [ "node", "/app/server.js" ]
